# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish Package (GitHub Packages)

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set node version to 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Dry run publish
        run: npm pack -dry-run

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
          retention-days: 1

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          path: .

      - name: Set npm registry url
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # registry-url: https://npm.pkg.github.com/
          scope: '@hhui64'

      - name: Dry run publish
        run: npm pack -dry-run

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish .
